config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("ep_crm_portal/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("pages.urls")),
]
if settings.DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]
    if settings.DEBUG and settings.DEBUG_TOOLBAR:
        urlpatterns = [
            path("__debug__/", (include("debug_toolbar.urls")))
        ] + urlpatterns

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("market_update", views.MarketUpdateView.as_view(), name="market_update"),
]

templates/_partials/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicons/favicon.png' %}"/>
    <!-- DataTables css -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.12.1/cr-1.5.6/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.12.1/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/datatables.min.css"/>


    <link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.2.3/css/fixedHeader.dataTables.min.css">


    <title>{% block html_title %}{% endblock html_title %}</title>
  </head>
  <body>

    <!-- ======= header ======= -->

    <header id="pageHead">
      <nav class="navbar navbar-expand-lg py-3 navbar-dark" style="background-color: #000000">
        <div class="container">
          <a href="#" class="navbar-brand">
            <!-- Logo Image -->
            <img src="{% static 'img/energy-portfolio-logo.png' %}" width="300px" height="130px" alt="Energy Portfolio Logo">
          </a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'pages:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:market_update' %}">Market Update</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Seamless Utilities</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Our Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Our Partners</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contract Us</a>
              </li>


            </ul>
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="#">Login</a>
              </li>
            </ul>

          </div>
        </nav>

      </header> <!-- End Header -->
      <br>
      <!-- Main Content -->
      <main id="pageMain">



        <!-- Page Content used in other pages -->

        {% block content %}{% endblock content %}


      </main> <!-- End Main -->
      <!-- Footer -->
      <footer id="footer">
        <div class="footer-top">
          <div class="container">
            <div class="row">
              <div class="col-md-9">
                <p>Tel: 0845 177 1376</p>
                <address>
                  Energy Portfolio Limited
                  43 Berkeley Square, London W1J 5FJ <br>
                  Registered in England and Wales no. 08100311
                </address>
              </div>
              <div class="col-md-3">
                <ul>
                  <li> <a href="privacy_policy">Privacy Policy</a></li>
                  <li> <a href="complaints_policy">Complaints Policy</a></li>


                </ul>
              </div>

            </div>
          </div>
        </div>

        <div class="container">
          <div class="copyright">
            &copy; Copyright <strong>Energy Portfolio Limited</strong>. All Rights Reserved {%now "Y"%}
          </div>
        </div>


      </footer>
      <!-- End Footer -->
      <!-- Modal -->



      <!-- Bootstrap JS -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <!-- JQuery CDN -->
      <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
      <!-- Messages timer script -->
      <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

      {% block extra_js %}

      {% endblock extra_js %}



    </body>
  </html>